### ISSUE TITLE
Show which inputs are required in the contact form

### ISSUE THREAD

**Issue by ko-karol** [fac26/Dominic-Gareth-Markup-Project#16]
Have some kind of indicator that a certain input is required to be able to submit the form, and then an indicator to show what that indicator is for.

**Comment by DominicSimpson** [comment]
Thank you for highlighting this, I'd completely forgot. I'll add a span class with a red star to indicate Required for each mandatory field. 🎗️

**Comment by ko-karol** [comment]
Great. Exactly what I meant. Thank you.
