### ISSUE TITLE
img names could be more concise, and img in folder looks cleaner

### ISSUE THREAD

**Issue by georgiaewhitney** [fac26/Dominic-Gareth-Markup-Project#17]
i.e 

sims.jpg instead of long automated name. 

and images in image folder looks a bit tidier as the site gets bigger and makes files easier to navigate

**Comment by georgiaewhitney** [comment]
Apologies - Ivan formatted this much better than I did, in issue #26 :)

**Comment by GalKJ** [comment]
# Thanks 😄 

100% will do this

**Comment by georgiaewhitney** [comment]
I'll close this issue as you can tackle Ivan's one with the same instruction :)
