### ISSUE TITLE
Images don't seem to resize properly.

### ISSUE THREAD

**Issue by ko-karol** [fac26/Dominic-Gareth-Markup-Project#22]
Think about adding media queries to your css and other ways to resize your images.

```css
@media only screen and (max-width: ####) {
}
```

**Comment by GalKJ** [comment]
Thanks 😄 

Media queries are great but stylistically we were happy with the images keeping their size, however we''ll bare this in mind 🧠

**Comment by ko-karol** [comment]
Great. Makes sense in this way. The screen size at which they become too big is miniscule enough to not bother with media queries.
