### ISSUE TITLE
contact form is fixed to the bottom, creates large white space on large screens

### ISSUE THREAD

**Issue by georgiaewhitney** [fac26/Dominic-Gareth-Markup-Project#24]
On larger screens the contact form remains at the bottom which creates a large gap of whitespace between the form and about me. Might be easier if the form floated with the bios and blank space created at the bottom.

**Comment by GalKJ** [comment]
Thanks 😄 

Our CSS is not yet finished and this is an issue we will be tackling 🏈 😄

**Comment by georgiaewhitney** [comment]
Cool - looking forward to seeing it all come together 👍
