### ISSUE TITLE
Try to use shorthand css classes to improve css readablility.

### ISSUE THREAD

**Issue by ko-karol** [fac26/Dominic-Gareth-Markup-Project#25]
```css
    body {
    max-width: 90vw;
    margin-left: auto;
    margin-right: auto;
    background-color: #eee8e8;
    margin-bottom: 20px;
```
you could probably use something like
```css 
  margin: 0 auto;
  margin-bottom: 20px;
``` 
instead of 
```css
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 20px;
```

**Comment by GalKJ** [comment]
Thanks ⭐ 

I would usually do as you've suggested but when looking through the CSS project documentation from FAC I saw they had opted to use 

`margin-left: auto;
  margin-right: auto;`

I will inquire as to why they  made this choice but I too like my rules concise 😄

**Comment by ko-karol** [comment]
Yup. No worries. Feel free to close this issue whenever.
