### ISSUE TITLE
Click to navigate to different sections of your webpage

### ISSUE THREAD

**Issue by GalKJ** [fac26/Dominic-Gareth-Markup-Project#3]
Look into different ways for the user to navigate to different sections

**Comment by GalKJ** [comment]
Hey Dom 

I've assigned myself to this issue alongside you so I can get started on the branch seen as i have the code from another project which we can use to navigate when clicking on a link. 

I'll create a new branch called `feature-issue3-clicknav` and create a script file there called `index.js`. If you need to create a .js file for anything just remember to call it the same name so we don't get a merge conflict down the line.

Cheers, Gal.

**Comment by GalKJ** [comment]
> I'll create a new branch called `feature-issue3-clicknav` and create a script file there called `index.js`. If you need to create a .js file for anything just remember to call it the same name so we don't get a merge conflict down the line.

Re: the above we won't need the `index.js` since this feature can be achieved with `HTML` only.

Add the `<a></a>` tag with an id that corresponds to where you want the user to navigate to 
`<a href="#add id here to navigate">Click me to navigate</a>` 

Then add an `id` which is the same as the one in the `<a></a>` tag above wherever you want the user to land when they click the `<a></a>` tag.

I'll create the `feature-issue3-clicknav` branch and add the new navigation code.

Gal

**Comment by DominicSimpson** [comment]
Thanks Gal, will do so. I'll clone this.
